version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ['--config=/etc/otelcol-contrib/config.yaml']
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
      - oltpcol-vol:/conf/oltpcol
      - type: bind
        source: './'
        target: '/conf/oltpcol'
    environment:
      - OTEL_EXPORTER_OTLP_TRACES_TIMEOUT=10s
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    depends_on:
      - jaeger-server
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - cluster.name=jaeger-cluster
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data

  jaeger-server:
    image: jaegertracing/all-in-one:latest
    restart: on-failure
    ports:
      - 16686:16686
    volumes:
      - jaeger-vol:/jaeger
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command:
      [
        '--es.server-urls=http://elasticsearch:9200',
        '--es.num-shards=1',
        '--es.num-replicas=0',
        '--log-level=error',
      ]
    depends_on:
      - elasticsearch

  orgsvc:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@orgsvc-db:5432/datab
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OLTP_HTTP_TRACE_ENDPOINT=http://otel-collector:4318/v1/traces
      - OLTP_HTTP_METER_ENDPOINT=http://otel-collector:4318/v1/metrics
    restart: always
    volumes:
      - svc-vol:/root
      - type: bind
        source: './'
        target: '/orgsvc'
    depends_on:
      - orgsvc-db
      - otel-collector
      - jaeger-server

  orgsvc-db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=datab
    ports:
      - '5432:5432'

  # --- Filebeat Service ---
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.0 # Match Elasticsearch version
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro # Mount your Filebeat config
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # For general Docker container logs
      - /var/run/docker.sock:/var/run/docker.sock:ro # For Docker metadata (container names, IDs, etc.)
    command: ['filebeat', '-e', '-strict.perms=false']
    user: root
    depends_on:
      - elasticsearch # Filebeat depends on Elasticsearch being up

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1 # Use a specific version, matching Elasticsearch
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # - ELASTICSEARCH_USERNAME=kibana_system # Default user for Kibana to connect to ES
      # - ELASTICSEARCH_PASSWORD=changeme # IMPORTANT: Change this if you change elastic user password
    depends_on:
      - elasticsearch

volumes:
  postgres_data:
  svc-vol:
  oltpcol-vol:
  jaeger-vol:
  esdata:
