"""unique contraints

Revision ID: 2b46878d84bc
Revises: 0d8e24df0bec
Create Date: 2025-03-30 11:12:39.771337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '2b46878d84bc'
down_revision: Union[str, None] = '0d8e24df0bec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_campaigns_name', table_name='campaigns')
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=True)
    op.create_unique_constraint("unique_questions_text", 'questions', ['question_text'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_questions_text", 'questions', type_='unique')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.create_index('ix_campaigns_name', 'campaigns', ['name'], unique=False)
    # ### end Alembic commands ###
